# Define the event and alert data structures used throughout the SIEM pipeline.
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Any

@dataclass
class Alert:
    # Represents a detection rule match and its associated metadata.
    rule: str
    severity: str
    description: str
    source_ip: str | None = None
    port: int | None = None

@dataclass
class SecurityEvent:
    # Core metadata for a security event.
    timestamp: str
    event_type: str
    severity: str

    # Optional network identifiers.
    source_ip: str | None = None
    destination_ip: str | None = None
    port: int | None = None
    protocol: str | None = None

    # Optional user or process details.
    username: str | None = None
    process: str | None = None

    # Original raw log text for traceability.
    raw_log: str | None = None

    # Enriched features for ML and analytics.
    features: Dict[str, Any] = field(default_factory=dict)

    # Alerts generated by detection rules.
    alerts: List["Alert"] = field(default_factory=list)

    # Computed risk score and risk level.
    risk_score: int = 0
    risk_level: str = "Informational"

    # Placeholder for future ML predictions.
    ml_prediction: Dict[str, Any] = field(default_factory=dict)


    def add_alert(self, rule, severity, description, **kwargs):
        # Attach a new alert object to the event.
        alert = Alert(
            rule=rule,
            severity=severity,
            description=description,
            source_ip=kwargs.get("source_ip"),
            port=kwargs.get("port")
        )
        self.alerts.append(alert)


    def set_risk(self, score, level):
        # Store the calculated risk score and descriptive level.
        self.risk_score = score
        self.risk_level = level


    def add_features(self, features):
        # Merge generated features into the event payload.
        self.features.update(features)


    def to_dict(self):
        # Convert the event and all nested data to a serializable dictionary.
        return {
            "timestamp": self.timestamp,
            "event_type": self.event_type,
            "severity": self.severity,

            "source_ip": self.source_ip,
            "destination_ip": self.destination_ip,
            "port": self.port,
            "protocol": self.protocol,

            "username": self.username,
            "process": self.process,

            "raw_log": self.raw_log,

            "features": self.features,

            "alerts": [
                {
                    "rule": alert.rule,
                    "severity": alert.severity,
                    "description": alert.description,
                    "source_ip": alert.source_ip,
                    "port": alert.port
                }
                for alert in self.alerts
            ],

            "risk": {
                "score": self.risk_score,
                "level": self.risk_level
            },

            "ml_prediction": self.ml_prediction
        }
    